name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and test in FreeBSD
      id: build
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y apache24

        run: |
          make
          make install
          install -m 0644 -o 0 -g 0 FreeBSD/2.0/001_mod_jail.conf /usr/local/etc/apache24/modules.d/
          service apache24 onestart
          jls
          service apache24 onestop
          jls
