name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and test in FreeBSD
      id: build
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        cpu: 4
        prepare: |
          pkg install -y apache24

        run: |
          make
          make install
          mv -f FreeBSD/files/001_mod_jail.conf.in 001_mod_jail.conf
          install -d -m 0644 -o 0 -g 0 001_mod_jail.conf.in /usr/local/etc/apache24/modules.d
          echo "ServerName localhost" >> /usr/local/etc/apache24/httpd.conf
          service apache24 onestart
          jls -v
          service apache24 onestop
          jls -v
